In [1]:
import cv2 as cv
import numpy as np

In [2]:
image=cv.imread("C:\\Users\\acer\\Desktop\\SEM 6 PPTS\MLL\\avengers\\number-2-number-two-svg-png-icon-download-6.png")
# gray = cv.cvtColor(image, cv.COLOR_BGR2GRAY)

In [3]:
print(image)

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


In [4]:
image.shape

(980, 980, 3)

In [5]:
cv.imshow("Image",image)
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(1)

-1

In [7]:
image.shape

(980, 980, 3)

In [8]:
corner=image[50:100,50:100]

In [9]:
cv.imshow("Corner", corner)
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(1)

-1

In [10]:
canvas = np.zeros((300, 300, 3), dtype = "uint8")
#RGB(255,255,255)
green = (0, 255, 0)
cv.line(canvas, (0, 0), (300, 300), green,4)
cv.imshow("Canvas", canvas)
cv.waitKey(0)

-1

In [11]:
red = (0, 0, 255)
cv.line(canvas, (300, 0), (0, 300), red, 3)
cv.imshow("Canvas", canvas)
cv.waitKey(0)

-1

In [12]:
M = np.float32([[1, 0, 25], [0, 1, 50]])
shifted = cv.warpAffine(image, M, (image.shape[1], image.shape[0]))
cv.imshow("Shifted Down and Right", shifted)
cv.waitKey(0)

-1

In [13]:
cv.imshow("Original", image)
(h, w) = image.shape[:2]

center = (w // 2, h // 2)
M = cv.getRotationMatrix2D(center, 45, 1.0)
rotated = cv.warpAffine(image, M, (w, h))
cv.imshow("Rotated by 45 Degrees", rotated)
cv.waitKey(0)

-1

In [14]:
cv.imshow("Original", image)
print(image.shape)
r = 150.0 / image.shape[1]
dim = (150, int(image.shape[0] * r))
resized = cv.resize(image, dim, interpolation = cv.INTER_AREA)
print(resized.shape)
cv.imshow("Resized (Width)", resized)
cv.waitKey(0)

(980, 980, 3)
(150, 150, 3)


-1

In [15]:
cv.imshow("Original", image)
flipped = cv.flip(image, 0)
cv.imshow("Flipped Horizontally", flipped)
cv.waitKey(0)

-1