In [1]:
import cv2 as cv
import numpy as np

In [2]:
image=cv.imread("/Users/nageshjadhav/Desktop/img.png")
# gray = cv.cvtColor(image, cv.COLOR_BGR2GRAY)

In [3]:
print(image)

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[171 106  97]
  [171 106  97]
  [171 106  97]
  ...
  [171 106  97]
  [171 106  97]
  [214 185 180]]

 [[171 106  97]
  [171 106  97]
  [171 106  97]
  ...
  [171 106  97]
  [171 106  97]
  [214 185 180]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


In [4]:
image.shape

(257, 464, 3)

In [3]:
cv.imshow("Image",image)
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(1)

-1

In [4]:
image.shape

(236, 214, 3)

In [8]:
corner=image[50:100,50:100]

In [7]:
cv.imshow("Corner", corner)
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(1)

-1

In [4]:
canvas = np.zeros((300, 300, 3), dtype = "uint8")
#RGB(255,255,255)
green = (0, 255, 0)
cv.line(canvas, (0, 0), (300, 300), green,4)
cv.imshow("Canvas", canvas)
cv.waitKey(0)

113

In [10]:
red = (0, 0, 255)
cv.line(canvas, (300, 0), (0, 300), red, 3)
cv.imshow("Canvas", canvas)
cv.waitKey(0)

-1

# Image Processing

In [11]:
# Image Translation
#The first row of the matrix is [1, 0, tx], where tx is the number of pixels we will shift the image left or right. 
#Negative values of tx will shift the image to the left and positive values will shift the image to the right
M = np.float32([[1, 0, 25], [0, 1, 50]])
shifted = cv.warpAffine(image, M, (image.shape[1], image.shape[0]))
cv.imshow("Shifted Down and Right", shifted)
cv.waitKey(0)

257
196


-1

In [15]:
# Rotation
cv.imshow("Original", image)
(h, w) = image.shape[:2]

center = (w // 2, h // 2)
M = cv.getRotationMatrix2D(center, 45, 1.0)
rotated = cv.warpAffine(image, M, (w, h))
cv.imshow("Rotated by 45 Degrees", rotated)
cv.waitKey(0)

-1

In [5]:

cv.imshow("Original", image)
print(image.shape)
r = 150.0 / image.shape[1]
dim = (150, int(image.shape[0] * r))
resized = cv.resize(image, dim, interpolation = cv.INTER_AREA)
print(resized.shape)
cv.imshow("Resized (Width)", resized)
cv.waitKey(0)

(257, 464, 3)
(83, 150, 3)


113

In [17]:

cv.imshow("Original", image)
flipped = cv.flip(image, 0)
cv.imshow("Flipped Horizontally", flipped)
cv.waitKey(0)

-1

In [ ]:
python opencv cheat sheet pdf